name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    container: centos/devtoolset-7-toolchain-centos7
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.6'

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sipgraph-centos7
        path: _build/prod/rel/sipgraph/*.tar.gz
